stages:
  - 2_build_and_install
  - 3_mvn_install

before_script:
  - pwd
  - echo $CI_COMMIT_REF_NAME
  - git remote -v
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_COMMIT_REF_NAME

after_script:
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_COMMIT_REF_NAME



1_build_test_java:
  stage: 2_build_and_install
  script:
    - mvn clean
    - mvn test

1_svarog-utils-dev-install:
  stage: 3_mvn_install
  script:
    - pwd
    - cd $CI_PROJECT_DIR/
    - pwd
    - mvn clean package org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy -DskipTests
  only:
    - dev
    - staging
    - main


