stages:
  - 2_build_and_install
  - 3_mvn_install
  - 4_sonarqube

before_script:
  - pwd
  - echo $CI_COMMIT_REF_NAME
  - git remote -v
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_COMMIT_REF_NAME

after_script:
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_COMMIT_REF_NAME



1_build_test_java:
  stage: 2_build_and_install
  script:
    - mvn clean
    - mvn test

1_svarog-utils-dev-install:
  stage: 3_mvn_install
  script:
    - pwd
    - cd $CI_PROJECT_DIR/
    - pwd
    - mvn clean package org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy -DskipTests
  only:
    - dev
    - staging
    - master



1_svarog-utils_sonarqube_backend:
  stage: 4_sonarqube
  script:
    - cd $CI_PROJECT_DIR/
    - mvn sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

2_svarog-utils-sonarqube_backend_publish:
  stage: 4_sonarqube
  script:
    - cd $CI_PROJECT_DIR/
    - mvn sonar:sonar -Dsonar.analysis.mode=publish -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Donar.gitlab.user_token access=a18878c7b5beb401ce2f847537c296b46a3902b8
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - staging
    - dev
  when: manual



